import { ItemCard, CoordCard } from './types'

export const MOCK_ITEM_CARDS: ItemCard[] = [
  // TOPS
  {
    id: 'top-001',
    name: 'パステルフリルブラウス',
    category: 'tops',
    brand: 'PINK MOON',
    color: '#ff9ec4',
    gradient: 'from-pink-300 via-purple-300 to-pink-400',
    emoji: '🌸',
    tags: ['フェミニン', 'ピンク', 'フリル', 'オフィス'],
    rarity: 'super-rare',
  },
  {
    id: 'top-002',
    name: 'Y2Kホログラムトップ',
    category: 'tops',
    brand: 'STAR DUST',
    color: '#c084fc',
    gradient: 'from-violet-400 via-fuchsia-400 to-pink-400',
    emoji: '⭐',
    tags: ['Y2K', 'ホログラム', 'パーティ', 'ラメ'],
    rarity: 'legend',
  },
  {
    id: 'top-003',
    name: 'ベビーブルーニット',
    category: 'tops',
    brand: 'DREAMY',
    color: '#93c5fd',
    gradient: 'from-blue-200 via-sky-300 to-blue-400',
    emoji: '☁️',
    tags: ['カジュアル', 'ニット', 'ブルー', 'ナチュラル'],
    rarity: 'rare',
  },
  {
    id: 'top-004',
    name: 'コギャルチェックシャツ',
    category: 'tops',
    brand: 'GALS PARADE',
    color: '#f59e0b',
    gradient: 'from-amber-300 via-yellow-400 to-orange-400',
    emoji: '🎀',
    tags: ['コギャル', 'チェック', 'ビンテージ', '90s'],
    rarity: 'rare',
  },
  {
    id: 'top-005',
    name: 'オーロラサテンキャミ',
    category: 'tops',
    brand: 'AURORA',
    color: '#34d399',
    gradient: 'from-emerald-300 via-teal-300 to-cyan-400',
    emoji: '✨',
    tags: ['オーロラ', 'サテン', 'ドレスアップ', 'きれいめ'],
    rarity: 'super-rare',
  },

  // BOTTOMS
  {
    id: 'bot-001',
    name: 'バルーンミニスカート',
    category: 'bottoms',
    brand: 'PINK MOON',
    color: '#f9a8d4',
    gradient: 'from-pink-300 via-rose-300 to-fuchsia-400',
    emoji: '🎀',
    tags: ['ミニ', 'バルーン', 'フェミニン', 'ピンク'],
    rarity: 'super-rare',
  },
  {
    id: 'bot-002',
    name: 'ローライズデニム',
    category: 'bottoms',
    brand: 'DENIM LAB',
    color: '#60a5fa',
    gradient: 'from-blue-400 via-indigo-400 to-blue-500',
    emoji: '👖',
    tags: ['デニム', 'ローライズ', 'Y2K', 'カジュアル'],
    rarity: 'rare',
  },
  {
    id: 'bot-003',
    name: 'プリーツチュールスカート',
    category: 'bottoms',
    brand: 'FAIRY TALE',
    color: '#a78bfa',
    gradient: 'from-violet-300 via-purple-400 to-fuchsia-400',
    emoji: '🧚',
    tags: ['チュール', 'プリーツ', 'フェアリー', 'ドレスアップ'],
    rarity: 'legend',
  },
  {
    id: 'bot-004',
    name: 'カーゴワイドパンツ',
    category: 'bottoms',
    brand: 'STREET STAR',
    color: '#6b7280',
    gradient: 'from-gray-400 via-slate-400 to-gray-500',
    emoji: '🖤',
    tags: ['カーゴ', 'ワイド', 'ストリート', 'ユニセックス'],
    rarity: 'normal',
  },

  // SHOES
  {
    id: 'shoe-001',
    name: 'クリアプラットフォームヒール',
    category: 'shoes',
    brand: 'CRYSTAL',
    color: '#e0f2fe',
    gradient: 'from-sky-200 via-cyan-200 to-blue-300',
    emoji: '👠',
    tags: ['クリア', 'プラットフォーム', 'Y2K', 'ドレスアップ'],
    rarity: 'legend',
  },
  {
    id: 'shoe-002',
    name: 'ホログラムスニーカー',
    category: 'shoes',
    brand: 'STAR RUNNER',
    color: '#c4b5fd',
    gradient: 'from-violet-300 via-pink-300 to-rose-300',
    emoji: '👟',
    tags: ['スニーカー', 'ホログラム', 'カジュアル', 'スポーティ'],
    rarity: 'super-rare',
  },
  {
    id: 'shoe-003',
    name: 'メリージェーンパンプス',
    category: 'shoes',
    brand: 'SWEET FEET',
    color: '#fca5a5',
    gradient: 'from-red-300 via-rose-300 to-pink-400',
    emoji: '🩰',
    tags: ['メリージェーン', 'フェミニン', 'ガーリー', 'レトロ'],
    rarity: 'rare',
  },

  // BAGS
  {
    id: 'bag-001',
    name: 'ミニパフバッグ',
    category: 'bag',
    brand: 'FLUFFY',
    color: '#fde68a',
    gradient: 'from-yellow-200 via-amber-300 to-yellow-400',
    emoji: '👜',
    tags: ['ミニ', 'パフ', 'ふわふわ', 'キュート'],
    rarity: 'super-rare',
  },
  {
    id: 'bag-002',
    name: 'Y2Kバタフライクラッチ',
    category: 'bag',
    brand: 'BUTTERFLY',
    color: '#d8b4fe',
    gradient: 'from-purple-300 via-fuchsia-300 to-pink-400',
    emoji: '🦋',
    tags: ['バタフライ', 'クラッチ', 'Y2K', 'パーティ'],
    rarity: 'legend',
  },
  {
    id: 'bag-003',
    name: 'チェーンショルダー',
    category: 'bag',
    brand: 'CHAIN GANG',
    color: '#94a3b8',
    gradient: 'from-slate-300 via-gray-300 to-zinc-400',
    emoji: '⛓️',
    tags: ['チェーン', 'ショルダー', 'エッジー', 'クール'],
    rarity: 'rare',
  },

  // COSME
  {
    id: 'cosme-001',
    name: 'ピンクメイクパレット',
    category: 'cosme',
    cosmeSubCategory: 'palette',
    brand: 'GLOW UP',
    color: '#fb7185',
    gradient: 'from-rose-300 via-pink-400 to-fuchsia-400',
    emoji: '💄',
    tags: ['ピンク', 'フェミニン', 'デイリー', 'ナチュラル'],
    rarity: 'rare',
  },
  {
    id: 'cosme-002',
    name: 'オーロラハイライター',
    category: 'cosme',
    cosmeSubCategory: 'base',
    brand: 'AURORA GLOW',
    color: '#e9d5ff',
    gradient: 'from-violet-200 via-pink-200 to-rose-300',
    emoji: '✨',
    tags: ['ハイライト', 'オーロラ', 'ツヤ', 'グロウ'],
    rarity: 'legend',
  },
  {
    id: 'cosme-003',
    name: 'Y2Kグリッタリップ',
    category: 'cosme',
    cosmeSubCategory: 'lip',
    brand: 'GLITTER KISS',
    color: '#f43f5e',
    gradient: 'from-red-400 via-rose-400 to-pink-500',
    emoji: '💋',
    tags: ['グリッター', 'リップ', 'Y2K', 'ビビッド'],
    rarity: 'super-rare',
  },
  {
    id: 'cosme-004',
    name: 'スモーキーアイパレット',
    category: 'cosme',
    cosmeSubCategory: 'eye',
    brand: 'NIGHT STAR',
    color: '#1e293b',
    gradient: 'from-slate-600 via-purple-700 to-slate-800',
    emoji: '🌙',
    tags: ['スモーキー', 'アイシャドウ', 'セクシー', 'ナイト'],
    rarity: 'rare',
  },
]

export const AI_COORD_THEMES = [
  { theme: 'フェアリーガール', description: '妖精みたいな可愛さ', emoji: '🧚' },
  { theme: 'Y2Kパーティ', description: 'キラキラ輝くパーティルック', emoji: '⭐' },
  { theme: 'ストリートクール', description: 'エッジが効いたクールスタイル', emoji: '🖤' },
  { theme: 'ナチュラルデイ', description: '自然体の柔らかいデイリー', emoji: '🌸' },
  { theme: 'プリンセス覚醒', description: '誰もが振り向くプリンセスルック', emoji: '👑' },
]

export const MOCK_COORD_CARDS: CoordCard[] = [
  {
    id: 'coord-001',
    name: 'フェアリーデイコーデ',
    date: '2026-09-01',
    deckCards: {
      tops: MOCK_ITEM_CARDS[0],
      bottoms: MOCK_ITEM_CARDS[6],
      shoes: MOCK_ITEM_CARDS[9],
      bag: MOCK_ITEM_CARDS[13],
      cosme: MOCK_ITEM_CARDS[15],
    },
    totalScore: 92,
    theme: 'フェアリーガール',
  },
  {
    id: 'coord-002',
    name: 'Y2Kナイトアウト',
    date: '2026-08-28',
    deckCards: {
      tops: MOCK_ITEM_CARDS[1],
      bottoms: MOCK_ITEM_CARDS[5],
      shoes: MOCK_ITEM_CARDS[10],
      bag: MOCK_ITEM_CARDS[14],
      cosme: MOCK_ITEM_CARDS[17],
    },
    totalScore: 98,
    theme: 'Y2Kパーティ',
  },
]

export const SLOT_CONFIG = [
  { key: 'tops' as const, label: 'トップス', emoji: '👚', color: 'from-pink-500 to-rose-500' },
  { key: 'bottoms' as const, label: 'ボトムス', emoji: '👗', color: 'from-purple-500 to-violet-500' },
  { key: 'shoes' as const, label: 'シューズ', emoji: '👠', color: 'from-blue-500 to-cyan-500' },
  { key: 'bag' as const, label: 'バッグ', emoji: '👜', color: 'from-amber-500 to-yellow-500' },
  { key: 'cosme' as const, label: 'コスメ', emoji: '💄', color: 'from-fuchsia-500 to-pink-500' },
]
